### ISSUE TITLE
Unable to call FirestoreClient.listen()

### ISSUE THREAD

**Issue by cachapa** [grpc/grpc-dart#215]
I'm not sure if this is the right place to report this, but I couldn't find a more appropriate repository.
I'm having issues listening to Firestore change events, and it's hard to know if I'm missing something or if I'm running into an issue with the gRPC setup.

Here is the code. The document `get` request works fine, but `listen` fails:

``` dart
import 'dart:async';

import 'package:googleapis/src/generated/google/firestore/v1/firestore.pbgrpc.dart';
import 'package:grpc/grpc.dart';

FirestoreClient firestore;
final projectId = "PROJECT_ID";
final databaseId = "(default)";
final database = "projects/$projectId/databases/$databaseId";
final documentPath = "$database/documents/test_collection/test_document";

Future<void> main() async {
  final channel = ClientChannel('firestore.googleapis.com');
  firestore = FirestoreClient(channel);

  // Works fine
  await getDocument();
  // Fails
  await listen();
}

getDocument() async {
  final request = GetDocumentRequest()
    ..name = documentPath;
  final document = await firestore.getDocument(request);
  print(document);
}

listen() async {
  final streamController = StreamController<ListenRequest>();

  firestore.listen(streamController.stream)
    .listen((data) => print(data));

  final documentsTarget = Target_DocumentsTarget()
    ..documents.add(documentPath);

  final target = Target()
    ..documents = documentsTarget;

  final request = ListenRequest()
    ..database = database
    ..addTarget = target;

  // Initiate request
  streamController.add(request);
}
```

I'm getting the following error which leads me to believe that either I'm missing an argument somewhere or the request isn't being correctly built:

```
Unhandled exception:
gRPC Error (3, Missing required http header 'google-cloud-resource-prefix' or query param 'database'.)
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

I based my code on the `grpc googleapis` example, so it's using the local grpc module, but I also tried pulling latest pub.dev package (grpc 2.0.0+1) with the same results.

**Comment by sigurdm** [comment]
I'm not sure what is happening here.
Perhaps try supplying a header/metadata google-cloud-resource-prefix (haven't tested this).
```dart
listen() async {
  final documentsTarget = Target_DocumentsTarget()
    ..documents.add(documentPath);

  final target = Target()
    ..documents = documentsTarget;

  final request = ListenRequest()
    ..database = database
    ..addTarget = target;
  firestore.listen(Stream.fromIterable([request]), options: CallOptions(metadata: {'google-cloud-resource-prefix': database}))
      .listen((data) => print(data));
}
```

**Comment by cachapa** [comment]
That worked, thanks @sigurdm!
I wonder if this is an issue with the protobuff definition. In that case it might make sense to report it somewhere.

**Comment by sigurdm** [comment]
I have raised an internal issue.
Thanks!
