### ISSUE TITLE
failed to protoc  "NoSuchMethodError: Closure call with mismatched arguments: function '_memberNamesSuffix' "

### ISSUE THREAD

**Issue by hjlp20150803** [grpc/grpc-dart#311]
failed to "protoc  ./*.proto --dart_out=grpc:./dart"

```
$ dart --version
Dart VM version: 2.9.0-11.0.dev.flutter-6489a0c68d (be) (Wed May 27 05:50:13 2020 +0000) on "macos_x64"
$ pub --version
Pub 2.8.3
$ pub global activate protoc_plugin 19.0.1
Package protoc_plugin is currently active at version 19.0.1.
Resolving dependencies... (2.6s)^C
$ protoc  ./*.proto --dart_out=grpc:./dart
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function '_memberNamesSuffix'
Receiver: Closure: (_SyncIterator<String>) => bool
Tried calling: _memberNamesSuffix()
Found: _memberNamesSuffix(_SyncIterator<String>) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      disambiguateName (package:protoc_plugin/names.dart:166:27)
#3      _unusedMemberNames (package:protoc_plugin/names.dart:419:17)
#4      messageMemberNames (package:protoc_plugin/names.dart:291:11)
#5      MessageGenerator.resolve (package:protoc_plugin/message_generator.dart:187:27)
#6      FileGenerator.resolve (package:protoc_plugin/file_generator.dart:183:9)
#7      link (package:protoc_plugin/linker.dart:24:7)
#8      CodeGenerator.generate.<anonymous closure> (package:protoc_plugin/code_generator.dart:92:7)
#9      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._complete (dart:async/future_impl.dart:519:7)
#14     Stream.fold.<anonymous closure> (dart:async/stream.dart:776:14)
#15     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#19     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#20     _StreamController._closeUnchecked (dart:async/stream_controller.dart:644:7)
#21     _StreamController.close (dart:async/stream_controller.dart:637:5)
#22     _Socket._onData (dart:io-patch/socket_patch.dart:2027:21)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#26     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#27     _StreamController._add (dart:async/stream_controller.dart:655:7)
#28     _StreamController.add (dart:async/stream_controller.dart:597:5)
#29     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1563:35)
#30     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1045:18)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
--dart_out: protoc-gen-dart: Plugin failed with status code 255.
```

**Comment by hjlp20150803** [comment]
I think this should be a bug, cause the same proto file is good when I use '$ protoc ./test.proto --go_out=grpc:./dart',but it's wrong with '$ protoc ./test.proto --dart_out=grpc:./dart'.

The problem should be here:
'string Create=11;',
it's good when I change it to
'string Create0=11;'

I am not sure if the 'Create' is the protected word.

```
$ pub --version
Pub 2.8.4

$ dart --version
Dart VM version: 2.9.0-13.0.dev.flutter-54adfeb93f (be) (Tue Jun 2 18:40:43 2020 +0000) on "macos_x64"

$ brew info dart
dart-lang/dart/dart: stable 2.8.4, devel 2.9.0-13.0.dev
The Dart SDK
https://dart.dev
Conflicts with:
  dart-beta (because dart-beta ships the same binaries)
/usr/local/Cellar/dart/2.8.4 (502 files, 486MB) *
  Built from source on 2020-06-05 at 09:50:05
From: https://github.com/dart-lang/homebrew-dart/blob/master/dart.rb
==> Options
--devel
	Install development version 2.9.0-13.0.dev
==> Caveats
Please note the path to the Dart SDK:
  /usr/local/opt/dart/libexec

test.proto:
syntax = "proto3";

package bridge;
//protoc-c --c_cout=.  *.proto
//protoc --go_out=. *.proto 
//protoc --dart_out=. *.proto

message AccessTime{
	string          Access=9;
	string          Write=10;
	string          Create=11;
}

$ protoc  ./test.proto --dart_out=grpc:./dart
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function '_memberNamesSuffix'
Receiver: Closure: (_SyncIterator<String>) => bool
Tried calling: _memberNamesSuffix()
Found: _memberNamesSuffix(_SyncIterator<String>) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      disambiguateName (package:protoc_plugin/names.dart:166:27)
#3      _unusedMemberNames (package:protoc_plugin/names.dart:419:17)
#4      messageMemberNames (package:protoc_plugin/names.dart:291:11)
#5      MessageGenerator.resolve (package:protoc_plugin/message_generator.dart:187:27)
#6      FileGenerator.resolve (package:protoc_plugin/file_generator.dart:183:9)
#7      link (package:protoc_plugin/linker.dart:24:7)
#8      CodeGenerator.generate.<anonymous closure> (package:protoc_plugin/code_generator.dart:92:7)
#9      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#13     Future._complete (dart:async/future_impl.dart:519:7)
#14     Stream.fold.<anonymous closure> (dart:async/stream.dart:776:14)
#15     _RootZone.runGuarded (dart:async/zone.dart:1372:10)
#16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:410:13)
#17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:420:15)
#18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:305:7)
#19     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#20     _StreamController._closeUnchecked (dart:async/stream_controller.dart:644:7)
#21     _StreamController.close (dart:async/stream_controller.dart:637:5)
#22     _Socket._onData (dart:io-patch/socket_patch.dart:2027:21)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
#26     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#27     _StreamController._add (dart:async/stream_controller.dart:655:7)
#28     _StreamController.add (dart:async/stream_controller.dart:597:5)
#29     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1563:35)
#30     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1045:18)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
--dart_out: protoc-gen-dart: Plugin failed with status code 255.
```

**Comment by sigurdm** [comment]
Yes, that looks like a bug.
Is there any chance you could narrow it down to a small `.proto` file that triggers this, and post it here?

**Comment by hjlp20150803** [comment]
> Yes, that looks like a bug.
> Is there any chance you could narrow it down to a small `.proto` file that triggers this, and post it here?

test.proto:
syntax = "proto3";

package bridge;
//protoc-c --c_cout=.  *.proto
//protoc --go_out=. *.proto 
//protoc --dart_out=. *.proto

message AccessTime{
	string          Access=9;
	string          Write=10;
	string          Create=11;//********
}
The bug is here "********",'Create',if you use 'Create0' to replace is ok.So I think maybe the 'Create' are used as protected word but it's not.

**Comment by sigurdm** [comment]
Sorry - I had not read your second message - it already contained the reproduction!

It seems to be an issue with pub precompiling protoc_plugin with one version of dart, and running it with another. 

'create' is indeed a reserved field name in dart. But the protoc_plugin should be able to rename it. But that code-path seems to trigger the problem.

For now I would suggest you to `pub global activate protoc_plugin` with the same version of pub as the dart version in your path.

I believe this will no longer be a problem when https://github.com/dart-lang/pub/pull/2493 is rolled into the sdk. It will make a precompilation specifically for the dart-version you are using, and recompile if the right one is not found.

**Comment by chipkent** [comment]
I also experienced this bug, when I recently upgraded flutter.  With multiple darts on my machine, I had to explicitly compile using the new flutter.

flutter pub global activate protoc_plugin

**Comment by mraleph** [comment]
Not a gRPC issue.
