### ISSUE TITLE
Client skips Server Exceptions

### ISSUE THREAD

**Issue by zs-dima** [grpc/grpc-dart#408]
Client skips `SecurityTokenExpiredException` fired by Server
Tested case: 
Client listening Server stream and `SecurityTokenExpiredException` appear on Server.
Client result stream finalized without any error - in the same way as Server returns empty stream - so exception fully skipped. 

grpc: ^2.8.0
Simplest ClientInterceptor used for the JWT authorization

```
Server-side exception:
Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
```

**Comment by mraleph** [comment]
We would need a runnable repro - without it we can't really help especially because it involves other languages than Dart. I would think that maybe server does not properly propagate the error to client.

**Comment by mraleph** [comment]
I will close for now, will reopen when reproduction is provided.
