### ISSUE TITLE
Error: Not found: 'dart:html'

### ISSUE THREAD

**Issue by medz** [grpc/grpc-dart#532]
output:
```bash
seven@147dda6e1ee9 app % flutter run
Launching lib/main.dart on iPhone 13 in debug mode...
Running Xcode build...
Xcode build done.                                           12.5s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder,
    name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:5AAB9288-4DAE-46F7-81AC-7AE173DD6F7F, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:FE1A7866-86C7-4EF6-A2AC-9A92833CD444, OS:15.0, name:iPad Air (4th generation)
    }
    { platform:iOS Simulator, id:A8F001F5-2AA2-4B8A-AF6A-C85A1EE3A70C, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:E7A1AF3E-CFBB-4211-84E7-3E2D12614203, OS:15.0, name:iPad Pro (11-inch) (3rd
    generation) }
    { platform:iOS Simulator, id:F1D8EAF4-9A6C-46C8-86C9-15542628BD28, OS:15.0, name:iPad Pro (12.9-inch) (5th
    generation) }
    { platform:iOS Simulator, id:42D18D1B-2A46-4105-AED0-884C434C6516, OS:15.0, name:iPad mini (6th
    generation) }
    { platform:iOS Simulator, id:B1A565E8-A48A-4AA1-B06E-6366611C0BC8, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:3E469E89-048F-4A1A-9538-EF70B8C84C47, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:676B4920-8635-48D0-A1E4-7D233C4FF9FA, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:A9AA184A-DADF-4E2E-81E0-E24173BE81E1, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:AC83861B-65D1-4B67-AC45-B8B1E000B78E, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:477AF76C-83BC-4384-88F0-7F630D1B994C, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:4708B71C-69AB-459A-96C6-B3DC0A2A6250, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:7D449F9F-5065-47A5-BAFC-42B7E7D35906, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:CD482D5E-E061-4444-90E1-F460CB03F9DC, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:17190BDF-120F-4C2E-8E05-FC467B613FAB, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:D703DC5B-DB35-40C3-8AAD-5114594F7701, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:90BBCE7F-2521-4A06-9B12-0AD5A1AB2937, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:40EA8706-734B-4BD4-99FC-24A8462B2C21, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:26DF018E-52EE-4BC9-A427-C4B0BBBA6EB9, OS:15.0, name:iPhone SE (2nd
    generation) }
    { platform:iOS Simulator, id:FA66E236-B107-4154-97EF-36C3D4024FBC, OS:15.0, name:iPod touch (7th
    generation) }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    ** BUILD FAILED **


Xcode's output:
↳
    Invalid depfile:
    /Users/seven/workspace/socfony/app/.dart_tool/flutter_build/81429ed4d57cf4548d9106edbc1ff402/kernel_snapsh
    ot.d
    Invalid depfile:
    /Users/seven/workspace/socfony/app/.dart_tool/flutter_build/81429ed4d57cf4548d9106edbc1ff402/kernel_snapsh
    ot.d
    Invalid depfile:
    /Users/seven/workspace/socfony/app/.dart_tool/flutter_build/81429ed4d57cf4548d9106edbc1ff402/kernel_snapsh
    ot.d
    Invalid depfile:
    /Users/seven/workspace/socfony/app/.dart_tool/flutter_build/81429ed4d57cf4548d9106edbc1ff402/kernel_snapsh
    ot.d
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:17:8:
    Error: Not found: 'dart:html'
    import 'dart:html';
           ^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/io_bits/io_bits_web.dart:16:1:
    Error: Not found: 'dart:html'
    export 'dart:html' show HttpStatus;
    ^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:33:9:
    Error: Type 'HttpRequest' not found.
      final HttpRequest _request;
            ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:159:27:
    Error: Type 'HttpRequest' not found.
      void _initializeRequest(HttpRequest request, Map<String, String> metadata) {
                              ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:169:3:
    Error: Type 'HttpRequest' not found.
      HttpRequest createHttpRequest() => HttpRequest();
      ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:133:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.ok: StatusCode.ok,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:134:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.badRequest: StatusCode.invalidArgument,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:135:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.unauthorized: StatusCode.unauthenticated,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:136:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.forbidden: StatusCode.permissionDenied,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:137:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.notFound: StatusCode.notFound,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:138:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.conflict: StatusCode.aborted,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:139:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.preconditionFailed: StatusCode.failedPrecondition,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:140:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.tooManyRequests: StatusCode.resourceExhausted,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:141:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.clientClosedRequest: StatusCode.cancelled,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:142:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.internalServerError: StatusCode.unknown,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:143:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.notImplemented: StatusCode.unimplemented,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:144:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.serviceUnavailable: StatusCode.unavailable,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/shared/status.dart:145:5: Error: Getter not
    found: 'HttpStatus'.
        HttpStatus.gatewayTimeout: StatusCode.deadlineExceeded,
        ^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:33:9:
    Error: 'HttpRequest' isn't a type.
      final HttpRequest _request;
            ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:61:14:
    Error: Getter not found: 'HttpRequest'.
            case HttpRequest.HEADERS_RECEIVED:
                 ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:64:14:
    Error: Getter not found: 'HttpRequest'.
            case HttpRequest.DONE:
                 ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:71:30:
    Error: 'ProgressEvent' isn't a type.
        _request.onError.listen((ProgressEvent event) {
                                 ^^^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:159:27:
    Error: 'HttpRequest' isn't a type.
      void _initializeRequest(HttpRequest request, Map<String, String> metadata) {
                              ^^^^^^^^^^^
    ../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart:169:38:
    Error: The method 'HttpRequest' isn't defined for the class 'XhrClientConnection'.
     - 'XhrClientConnection' is from 'package:grpc/src/client/transport/xhr_transport.dart'
     ('../../../.pub-cache/hosted/pub.dartlang.org/grpc-3.0.2/lib/src/client/transport/xhr_transport.dart').
    Try correcting the name to the name of an existing method, or defining a method named 'HttpRequest'.
      HttpRequest createHttpRequest() => HttpRequest();
                                         ^^^^^^^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only
    supports file:* and data:* URIs)
    #0      StandardFileSystem.entityForUri
    (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:614:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:754:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:570:9)
    <asynchronous suspension>
    #4      starter (package:flutter_frontend_server/server.dart:85:12)
    <asynchronous suspension>
    #5      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
    <asynchronous suspension>
    Failed to package /Users/seven/workspace/socfony/app.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

Could not build the application for the simulator.
Error launching application on iPhone 13.
```

doctor:
```bash
seven@147dda6e1ee9 app % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.2)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by medz** [comment]
code: https://github.com/odroe/socfony/tree/main/app

**Comment by medz** [comment]
I relied on the file by mistake. Sorry

**Comment by kaysman** [comment]
Can you share how you solved this or found any reference?
