### ISSUE TITLE
Bad state: Cannot add event after closing

### ISSUE THREAD

**Issue by 4ntoine** [grpc/grpc-dart#552]
<short description>

3.0.2

## Repro steps

The server might be closed or broken.

```
Future<Instance> getCliInstance(ServiceClient client) async {
    
      var message1 = "Creating cli instance...";
      if (kDebugMode)
        print(message1);
      FirebaseCrashlytics.instance.log(message1);
      final createResponse = await client.create(CreateRequest.getDefault()); // crashes here
...
}

// CLI instance
    try {
      await InitResponseHolder.get().getCliInstance(client);
    } catch (e, st) { // not catched
      if (!silent) {
        // we might don't need reporting as it's not the last attempt
        FirebaseAnalytics.instance.logEvent(name: 'get_cli_instance_failed');
        FirebaseCrashlytics.instance.recordError(e, st, fatal: false);
      } else {
        FirebaseCrashlytics.instance.log('Failed to connect: $e');
      }
      return false;
    } finally {
      await Requests.releaseCliChannel();
    }
...
```

Expected result: error not thrown or catched

Actual result: error thrown

## Details

```
2022-05-16 23:07:29.877 I/flutter: Bad state: Cannot add event after closing
2022-05-16 23:07:29.879 I/flutter: #0      _StreamController.add (dart:async/stream_controller.dart:595:24)
    #1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:867:13)
    #2      _rootRunUnary (dart:async/zone.dart:1434:47)
    #3      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
    #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
    #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
    #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
    #7      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
    #8      _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
    #9      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
    #10     _rootRunUnary (dart:async/zone.dart:1434:47)
    #11     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
    #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
    #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
    #14     _BufferingStreamSubs
```

**Comment by osa1** [comment]
Closing as this doesn't have a reproducer. Please provide a reproducer so that we can try and debug this, and re-open the issue.
