### ISSUE TITLE
"Null check operator used on a null value" on "ServerHandler_.sendTrailers/ServerHandler_._sendError"

### ISSUE THREAD

**Issue by fzyzcjy** [grpc/grpc-dart#568]
Hi thanks for the library! However I see NPE errors when using 3.0.3.

Full error log:

```
[19:10:15|manager]: Unhandled exception:
[19:10:15|manager]: Null check operator used on a null value
[19:10:15|manager]: #0      ServerHandler_.sendTrailers (package:grpc/src/server/handler.dart:350:21)
[19:10:15|manager]: #1      ServerHandler_._sendError (package:grpc/src/server/handler.dart:420:5)
[19:10:15|manager]: #2      ServerHandler_._onResponse (package:grpc/src/server/handler.dart:293:7)
[19:10:15|manager]: #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
[19:10:15|manager]: #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
[19:10:15|manager]: #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
[19:10:15|manager]: #6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
[19:10:15|manager]: #7      _StreamController._add (dart:async/stream_controller.dart:648:7)
[19:10:15|manager]: #8      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:248:18)
[19:10:15|manager]: <asynchronous suspension>
[19:10:15|manager]: #9      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:247:17)
[19:10:15|manager]: <asynchronous suspension>
```

**Comment by osa1** [comment]
> when using 3.0.3

Is this a typo? Latest version is 3.0.2, and that's also the version used in master branch.

I briefly looked at the code and from the stack trace you shared it seems like you're using an older version. Could you try with the latest version?

**Comment by fzyzcjy** [comment]
Oh seems like a typo. I will try the latest.
