### ISSUE TITLE
Helloworld server crash (and is very slow)

### ISSUE THREAD

**Issue by NicolasJacob** [grpc/grpc-dart#67]
Run server from hello world example.
Run client and kill it. Repeat many time
Time to time, killing the client cause server crash. See trace bellow.

Also  the client is very slow (4 request per sec). Don't know if related or not.

GRPC Version : from the repository (../..) (0.4.0 ?)

## Repro steps
See above.

## Details

Server Stack Trace:
```
Unhandled exception:
Bad state: Cannot add event after closing
#0      _StreamController.add (dart:async/stream_controller.dart:584)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:858)
#2      TransportStream.sendHeaders (package:http2/transport.dart:241:10)
#3      ServerHandler.sendTrailers (package:grpc/src/server/handler.dart:310:13)
#4      ServerHandler._sendError (package:grpc/src/server/handler.dart:359:5)
#5      ServerHandler._onResponse (package:grpc/src/server/handler.dart:248:7)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
```

My Quick and dirty workaround : handler.dart: 248
      try {
        _sendError(grpcError);
      } catch(err) {
        print(err);
      }

**Comment by arsenchen** [comment]
If you sleep 10 seconds in sayHello function, run client and exit in 10 seconds,  it will always crash in the demo.
for example:
```
class GreeterService extends GreeterServiceBase {
  @override
  Future<HelloReply> sayHello(ServiceCall call, HelloRequest request) async {
    await new Future.delayed(new Duration(seconds: 10));
    return new HelloReply()..message = 'Hello, ${request.name}!';
  }
}
```
stack:
```
Unhandled exception:
NoSuchMethodError: The method 'remove' was called on null.
Receiver: null
Tried calling: remove(":status")
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      ServerHandler.sendTrailers (package:grpc/src/server/handler.dart:295:23)
#2      ServerHandler._sendError (package:grpc/src/server/handler.dart:359:5)
#3      ServerHandler._onResponse (package:grpc/src/server/handler.dart:248:7)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#8      _StreamController._add (dart:async/stream_controller.dart:639)
#9      new Stream.fromFuture.<anonymous closure> (dart:async/stream.dart:107)
#10     _RootZone.runUnary (dart:async/zone.dart:1381)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#12     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#13     _Future._propagateToListeners (dart:async/future_impl.dart:662)
#14     _Future._complete (dart:async/future_impl.dart:467)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51)
#16     _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:292)
#17     GreeterService.sayHello (file:///Users/chenxinxin/code/grpc-dart/example/helloworld/bin/server.dart:28:5)
#18     _RootZone.runUnary (dart:async/zone.dart:1381)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#20     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#21     _Future._propagateToListeners (dart:async/future_impl.dart:662)
#22     _Future._complete (dart:async/future_impl.dart:467)
#23     new Future.delayed.<anonymous closure> (dart:async/future.dart:310)
#24     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#25     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#26     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by mit-mit** [comment]
cc @sigurdm

**Comment by p30arena** [comment]
is this still an issue?

I'm going to use grpc in a real project.
Flutter was still in beta but it didn't let me down.

**Comment by Xyzcancer** [comment]
Will it be fixed? 
I'm connecting to server -> send message to StreamController -> reload app -> subscribe on stream and send message again -> it leads to server crash. Bad state: Cannot add event after closing

**Comment by HyprUsr** [comment]
is this issue still open? any idea how to fix it?

**Comment by mosuem** [comment]
Hi, please do upvote or provide details if you are also experiencing this bug! I have no direct plans to dive into this at the moment, as I am working on other issues.

**Comment by HyprUsr** [comment]
this is the error I'm getting:

error: 
```
Bad state: Cannot add event after closing
```

stack trace:
```
[
  "#0 _StreamController.add (dart:async/stream_controller.dart:617)",
  "#1 _StreamSinkWrapper.add (dart:async/stream_controller.dart:898)",
  "#2 ServerHandler._onDataActive (package:grpc/src/server/handler.dart:297)",
  "#3 _rootRunUnary (dart:async/zone.dart:1538)",
  "#4 _CustomZone.runUnary (dart:async/zone.dart:1429)",
  "#5 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1329)",
  "#6 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381)",
  "#7 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312)",
  "#8 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)",
  "#9 _EventSinkWrapper.add (dart:async/stream_transformers.dart:13)",
  "#10 grpcDecompressor.<anonymous closure> (package:grpc/src/shared/message.dart:102)",
  "#11 _HandlerEventSink.add (dart:async/stream_transformers.dart:230)",
  "#12 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:115)",
  "#13 _rootRunUnary (dart:async/zone.dart:1538)",
  "#14 _CustomZone.runUnary (dart:async/zone.dart:1429)",
  "#15 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1329)",
  "#16 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381)",
  "#17 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312)",
  "#18 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)",
  "#19 _EventSinkWrapper.add (dart:async/stream_transformers.dart:13)",
  "#20 _GrpcMessageConversionSink._addData (package:grpc/src/shared/streams.dart:117)",
  "#21 _GrpcMessageConversionSink.add (package:grpc/src/shared/streams.dart:163)",
  "#22 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:70)",
  "#23 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:115)",
  "#24 _rootRunUnary (dart:async/zone.dart:1546)",
  "#25 _CustomZone.runUnary (dart:async/zone.dart:1429)",
  "#26 _CustomZone.runUnaryGuarded (dart:async/zone.dart:1329)",
  "#27 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381)",
  "#28 _DelayedData.perform (dart:async/stream_impl.dart:573)",
  "#29 _PendingEvents.handleNext (dart:async/stream_impl.dart:678)",
  "#30 _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:649)",
  "#31 _rootRun (dart:async/zone.dart:1517)",
  "#32 _CustomZone.run (dart:async/zone.dart:1422)",
  "#33 _CustomZone.runGuarded (dart:async/zone.dart:1321)",
  "#34 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1362)",
  "#35 _rootRun (dart:async/zone.dart:1525)",
  "#36 _CustomZone.run (dart:async/zone.dart:1422)",
  "#37 _CustomZone.runGuarded (dart:async/zone.dart:1321)",
  "#38 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1362)",
  "#39 _microtaskLoop (dart:async/schedule_microtask.dart:40)",
  "#40 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)",
  "#41 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:127)",
  "#42 _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:194)",
  ""
]
```

as I see it's the same error but has a different stacktrace 🤔 should I open a different issue?
it happens quite often on my gRPC server and kills the server

**Comment by mosuem** [comment]
A minimal working example would go a long way in helping to debug this, and see if it's the same issue.

**Comment by HyprUsr** [comment]
I genuinely don't know what triggers it or how to reproduce it 😅 
there is no clue in the stack trace pointing to my application file

**Comment by HyprUsr** [comment]
could it be because of this block?
https://github.com/grpc/grpc-dart/blob/master/lib/src/server/server.dart#L165

**Comment by HyprUsr** [comment]
Update:
I've split the services to instances based on service and I realized it's only happening in the service that I have both stream request and stream response.

my proto definition:
```
service ChatService {
  rpc StreamChatEvent(stream StreamChatEventRequest) returns (stream StreamChatEventResponse);
}
```

and here's my server side implementation:
```
class ChatService extends ChatServiceBase {
  @override
  Stream<StreamChatEventResponse> streamChatEvent(
    grpc.ServiceCall call,
    Stream<StreamChatEventRequest> requestStream,
  ) {
    final controller = StreamResponse<StreamChatEventResponse>();

    unawaited(() async {
      onBlaBlaHappened((event) {
        controller.add(
         StreamChatEventResponse(
            event: event,
          ),
        );
      });

      await for (final request in requestStream) {
        await _handleRequest(
          request: request,
        );
      }
    }());

    return controller.stream;
  }
}


class StreamResponse<T> {
  final _controller = StreamController<T>();

  Stream<T> get stream => _controller.stream;

  void add(T event) {
    if (!_controller.isClosed) {
      try {
        _controller.add(event);
      } on StateError {
        close();
      }
    }
  }

  void addError(Object event, [StackTrace? stackTrace]) {
    if (!_controller.isClosed) {
      try {
        _controller.addError(event, stackTrace);
      } on StateError {
        close();
      }
    }
  }

  void close() {
    if (!_controller.isClosed) {
      unawaited(_controller.close());
    }
  }
}
```
