### ISSUE TITLE
`timeline_test` failure on Windows.

### ISSUE THREAD

**Issue by mosuem** [grpc/grpc-dart#697]
The `timeline_test` has been failing on Windows since at least Dart `3.4.0-185.0.dev`, last working version was `3.4.0-160.0.dev`.
Could not be reproduced locally.

**Comment by mraleph** [comment]
@derekxu @bkonyi are there some known issues with vm-service / DDS?

We are getting:

```
Run dart run --enable-vm-service --timeline-streams=Dart test/timeline_test.dart
vm-service: Error: Unhandled exception:
FormatException: Unexpected character (at character 1)
Could not find a command named "/hostedtoolcache/windows/dart/3.4.0-260.0.d...
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:124[7](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:8):9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      _DebuggingSession.start.<anonymous closure> (dart:vmservice_io:132:27)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#[8](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:9)      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#[9](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:10)      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#12     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#13     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#14     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#15     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#16     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#17     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:[10](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:11))
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:[11](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:12))
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#22     _StreamController._add (dart:async/stream_controller.dart:658:7)
#23     _StreamController.add (dart:async/stream_controller.dart:606:5)
#24     _Socket._onData (dart:io-patch/socket_patch.dart:2449:41)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#29     _StreamController._add (dart:async/stream_controller.dart:658:7)
#30     _StreamController.add (dart:async/stream_controller.dart:606:5)
#31     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#32     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)

Unhandled exception:
FormatException: Unexpected character (at character 1)
Could not find a command named "/hostedtoolcache/windows/dart/3.4.0-260.0.d...
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1380:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:[12](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:13)47:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:912:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
#4      JsonDecoder.convert (dart:convert/json.dart:610:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      _DebuggingSession.start.<anonymous closure> (dart:vmservice_io:[13](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:14)2:27)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#12     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#13     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#[14](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:15)     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#[15](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:16)     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#[16](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:17)     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#[17](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:18)     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#[18](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:19)     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#20     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#21     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:[19](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:20))
#22     _StreamController._add (dart:async/stream_controller.dart:658:7)
#23     _StreamController.add (dart:async/stream_controller.dart:606:5)
#24     _Socket._onData (dart:io-patch/socket_patch.dart:2449:41)
#25     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#26     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#27     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#28     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#29     _StreamController._add (dart:async/stream_controller.dart:658:7)
#30     _StreamController.add (dart:async/stream_controller.dart:606:5)
#31     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#32     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:40:[21](https://github.com/grpc/grpc-dart/actions/runs/8513778379/job/23336919234?pr=695#step:8:22))
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#36     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
00:00 +0: Test gRPC timeline logging
```

Maybe some issue with paths on Windows?

**Comment by mraleph** [comment]
cc @derekxu16

**Comment by mosuem** [comment]
Yes, the fix is already landed in https://dart-review.googlesource.com/c/sdk/+/360920.
